### ISSUE TITLE
Sovremmeny-class RBUs not working

### ISSUE THREAD

**Issue by Neko014** [Dot-M134/ColdWaters-DotMod#45] opened 2021-09-20 07:21 UTC
The RBUs on the sovremmeny-class is not working even under 1km range, it says RBUs firing but nothing happened

**Comment by HobbitJack** [comment] 2021-09-21 21:10
Seems to be a unit bug. Not surprised.

Reports fine while using Imperial, broken in Metric. Confirmed.

**Comment by HobbitJack** [comment] 2021-09-23 23:24
Problem will be fixed in 0.2b.

**Closed by HobbitJack** 2021-09-23 23:24 UTC
Labels: bug, solved
